version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/myapp
    domainname: rad.cat.localhost
    hostname: rad.cat.localhost
    container_name: rad.cat.localhost
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      STATIC_SITE_BUILD: 1
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: radcat_development
    ports:
      - '33308:3306'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
